server:
  port: 6005

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/healthmax?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
#      ddl-auto: update
    #      ddl_auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: true
    database-platform:
      org.hibernate.dialect.MySQL8Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
